# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('resource-unit', ['core'])
    module.source = [
        'model/resource-unit.cc',
        'helper/resource-unit-container.cc',
        'helper/resource-unit-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('resource-unit')
    module_test.source = [
        'test/resource-unit-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/resource-unit-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'resource-unit'
    headers.source = [
        'model/resource-unit.h',
        'helper/resource-unit-container.h',
        'helper/resource-unit-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

