# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')
def configure(conf):
    #root_dir = conf.path.abspath()
    #example_lib_dir = os.path.join(root_dir, "libs/example-lib")
    example_lib_dir = "/usr/lib/"
    conf.env.append_value("LINKFLAGS", 
        ["-L%s/" % example_lib_dir])
    conf.env.append_value("LIB", ["boost_serialization"])
    conf.env.append_value("CPPFLAGS", 
        ["/usr/include/boost/", ])

def build(bld):
    module = bld.create_ns3_module('task', ['core'])
    module.source = [
        'model/task.cc',
        'helper/task-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('task')
    module_test.source = [
        'test/task-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/task-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'task'
    headers.source = [
        'model/task.h',
        'helper/task-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

